//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ClinVitta.ServiceUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.AutenticaUsuarioSoap")]
    public interface AutenticaUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PARAMETRO_xxx_WEBSERV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BuscaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginBuscaUsuario(string pUsuario, string pSenha, string pCodProjeto, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceUsuario.DadosUsuario[] EndBuscaUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ValidaToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginValidaToken(string pToken, string CODPROJETO, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceUsuario.DadosUsuario[] EndValidaToken(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
                this.RaisePropertyChanged("Any1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusField;
        
        private string cODUSUARIOField;
        
        private string filialUsuarioField;
        
        private string funcaoUsuarioField;
        
        private string nomeUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODUSUARIO {
            get {
                return this.cODUSUARIOField;
            }
            set {
                this.cODUSUARIOField = value;
                this.RaisePropertyChanged("CODUSUARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FilialUsuario {
            get {
                return this.filialUsuarioField;
            }
            set {
                this.filialUsuarioField = value;
                this.RaisePropertyChanged("FilialUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FuncaoUsuario {
            get {
                return this.funcaoUsuarioField;
            }
            set {
                this.funcaoUsuarioField = value;
                this.RaisePropertyChanged("FuncaoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
                this.RaisePropertyChanged("NomeUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutenticaUsuarioSoapChannel : ClinVitta.ServiceUsuario.AutenticaUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PARAMETRO_xxx_WEBSERVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PARAMETRO_xxx_WEBSERVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuscaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BuscaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceUsuario.DadosUsuario[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceUsuario.DadosUsuario[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidaTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidaTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceUsuario.DadosUsuario[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceUsuario.DadosUsuario[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticaUsuarioSoapClient : System.ServiceModel.ClientBase<ClinVitta.ServiceUsuario.AutenticaUsuarioSoap>, ClinVitta.ServiceUsuario.AutenticaUsuarioSoap {
        
        private BeginOperationDelegate onBeginPARAMETRO_xxx_WEBSERVDelegate;
        
        private EndOperationDelegate onEndPARAMETRO_xxx_WEBSERVDelegate;
        
        private System.Threading.SendOrPostCallback onPARAMETRO_xxx_WEBSERVCompletedDelegate;
        
        private BeginOperationDelegate onBeginBuscaUsuarioDelegate;
        
        private EndOperationDelegate onEndBuscaUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onBuscaUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginValidaTokenDelegate;
        
        private EndOperationDelegate onEndValidaTokenDelegate;
        
        private System.Threading.SendOrPostCallback onValidaTokenCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AutenticaUsuarioSoapClient() {
        }
        
        public AutenticaUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticaUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticaUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticaUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PARAMETRO_xxx_WEBSERVCompletedEventArgs> PARAMETRO_xxx_WEBSERVCompleted;
        
        public event System.EventHandler<BuscaUsuarioCompletedEventArgs> BuscaUsuarioCompleted;
        
        public event System.EventHandler<ValidaTokenCompletedEventArgs> ValidaTokenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPARAMETRO_xxx_WEBSERV(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
            return base.Channel.EndPARAMETRO_xxx_WEBSERV(result);
        }
        
        private System.IAsyncResult OnBeginPARAMETRO_xxx_WEBSERV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).BeginPARAMETRO_xxx_WEBSERV(callback, asyncState);
        }
        
        private object[] OnEndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
            ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult retVal = ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).EndPARAMETRO_xxx_WEBSERV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPARAMETRO_xxx_WEBSERVCompleted(object state) {
            if ((this.PARAMETRO_xxx_WEBSERVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PARAMETRO_xxx_WEBSERVCompleted(this, new PARAMETRO_xxx_WEBSERVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PARAMETRO_xxx_WEBSERVAsync() {
            this.PARAMETRO_xxx_WEBSERVAsync(null);
        }
        
        public void PARAMETRO_xxx_WEBSERVAsync(object userState) {
            if ((this.onBeginPARAMETRO_xxx_WEBSERVDelegate == null)) {
                this.onBeginPARAMETRO_xxx_WEBSERVDelegate = new BeginOperationDelegate(this.OnBeginPARAMETRO_xxx_WEBSERV);
            }
            if ((this.onEndPARAMETRO_xxx_WEBSERVDelegate == null)) {
                this.onEndPARAMETRO_xxx_WEBSERVDelegate = new EndOperationDelegate(this.OnEndPARAMETRO_xxx_WEBSERV);
            }
            if ((this.onPARAMETRO_xxx_WEBSERVCompletedDelegate == null)) {
                this.onPARAMETRO_xxx_WEBSERVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPARAMETRO_xxx_WEBSERVCompleted);
            }
            base.InvokeAsync(this.onBeginPARAMETRO_xxx_WEBSERVDelegate, null, this.onEndPARAMETRO_xxx_WEBSERVDelegate, this.onPARAMETRO_xxx_WEBSERVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.BeginBuscaUsuario(string pUsuario, string pSenha, string pCodProjeto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBuscaUsuario(pUsuario, pSenha, pCodProjeto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceUsuario.DadosUsuario[] ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.EndBuscaUsuario(System.IAsyncResult result) {
            return base.Channel.EndBuscaUsuario(result);
        }
        
        private System.IAsyncResult OnBeginBuscaUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pUsuario = ((string)(inValues[0]));
            string pSenha = ((string)(inValues[1]));
            string pCodProjeto = ((string)(inValues[2]));
            return ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).BeginBuscaUsuario(pUsuario, pSenha, pCodProjeto, callback, asyncState);
        }
        
        private object[] OnEndBuscaUsuario(System.IAsyncResult result) {
            ClinVitta.ServiceUsuario.DadosUsuario[] retVal = ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).EndBuscaUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBuscaUsuarioCompleted(object state) {
            if ((this.BuscaUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BuscaUsuarioCompleted(this, new BuscaUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BuscaUsuarioAsync(string pUsuario, string pSenha, string pCodProjeto) {
            this.BuscaUsuarioAsync(pUsuario, pSenha, pCodProjeto, null);
        }
        
        public void BuscaUsuarioAsync(string pUsuario, string pSenha, string pCodProjeto, object userState) {
            if ((this.onBeginBuscaUsuarioDelegate == null)) {
                this.onBeginBuscaUsuarioDelegate = new BeginOperationDelegate(this.OnBeginBuscaUsuario);
            }
            if ((this.onEndBuscaUsuarioDelegate == null)) {
                this.onEndBuscaUsuarioDelegate = new EndOperationDelegate(this.OnEndBuscaUsuario);
            }
            if ((this.onBuscaUsuarioCompletedDelegate == null)) {
                this.onBuscaUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBuscaUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginBuscaUsuarioDelegate, new object[] {
                        pUsuario,
                        pSenha,
                        pCodProjeto}, this.onEndBuscaUsuarioDelegate, this.onBuscaUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.BeginValidaToken(string pToken, string CODPROJETO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidaToken(pToken, CODPROJETO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceUsuario.DadosUsuario[] ClinVitta.ServiceUsuario.AutenticaUsuarioSoap.EndValidaToken(System.IAsyncResult result) {
            return base.Channel.EndValidaToken(result);
        }
        
        private System.IAsyncResult OnBeginValidaToken(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pToken = ((string)(inValues[0]));
            string CODPROJETO = ((string)(inValues[1]));
            return ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).BeginValidaToken(pToken, CODPROJETO, callback, asyncState);
        }
        
        private object[] OnEndValidaToken(System.IAsyncResult result) {
            ClinVitta.ServiceUsuario.DadosUsuario[] retVal = ((ClinVitta.ServiceUsuario.AutenticaUsuarioSoap)(this)).EndValidaToken(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidaTokenCompleted(object state) {
            if ((this.ValidaTokenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidaTokenCompleted(this, new ValidaTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidaTokenAsync(string pToken, string CODPROJETO) {
            this.ValidaTokenAsync(pToken, CODPROJETO, null);
        }
        
        public void ValidaTokenAsync(string pToken, string CODPROJETO, object userState) {
            if ((this.onBeginValidaTokenDelegate == null)) {
                this.onBeginValidaTokenDelegate = new BeginOperationDelegate(this.OnBeginValidaToken);
            }
            if ((this.onEndValidaTokenDelegate == null)) {
                this.onEndValidaTokenDelegate = new EndOperationDelegate(this.OnEndValidaToken);
            }
            if ((this.onValidaTokenCompletedDelegate == null)) {
                this.onValidaTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidaTokenCompleted);
            }
            base.InvokeAsync(this.onBeginValidaTokenDelegate, new object[] {
                        pToken,
                        CODPROJETO}, this.onEndValidaTokenDelegate, this.onValidaTokenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ClinVitta.ServiceUsuario.AutenticaUsuarioSoap CreateChannel() {
            return new AutenticaUsuarioSoapClientChannel(this);
        }
        
        private class AutenticaUsuarioSoapClientChannel : ChannelBase<ClinVitta.ServiceUsuario.AutenticaUsuarioSoap>, ClinVitta.ServiceUsuario.AutenticaUsuarioSoap {
            
            public AutenticaUsuarioSoapClientChannel(System.ServiceModel.ClientBase<ClinVitta.ServiceUsuario.AutenticaUsuarioSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("PARAMETRO_xxx_WEBSERV", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult _result = ((ClinVitta.ServiceUsuario.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult)(base.EndInvoke("PARAMETRO_xxx_WEBSERV", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBuscaUsuario(string pUsuario, string pSenha, string pCodProjeto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pUsuario;
                _args[1] = pSenha;
                _args[2] = pCodProjeto;
                System.IAsyncResult _result = base.BeginInvoke("BuscaUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceUsuario.DadosUsuario[] EndBuscaUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceUsuario.DadosUsuario[] _result = ((ClinVitta.ServiceUsuario.DadosUsuario[])(base.EndInvoke("BuscaUsuario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValidaToken(string pToken, string CODPROJETO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = pToken;
                _args[1] = CODPROJETO;
                System.IAsyncResult _result = base.BeginInvoke("ValidaToken", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceUsuario.DadosUsuario[] EndValidaToken(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceUsuario.DadosUsuario[] _result = ((ClinVitta.ServiceUsuario.DadosUsuario[])(base.EndInvoke("ValidaToken", _args, result)));
                return _result;
            }
        }
    }
}
