//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ClinVitta.ServiceCEP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCEP.PesquisaCEPSoap")]
    public interface PesquisaCEPSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BuscarCEP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginBuscarCEP(string pNumCEP, System.AsyncCallback callback, object asyncState);
        
        string EndBuscarCEP(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PesquisaCEPSoapChannel : ClinVitta.ServiceCEP.PesquisaCEPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuscarCEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BuscarCEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesquisaCEPSoapClient : System.ServiceModel.ClientBase<ClinVitta.ServiceCEP.PesquisaCEPSoap>, ClinVitta.ServiceCEP.PesquisaCEPSoap {
        
        private BeginOperationDelegate onBeginBuscarCEPDelegate;
        
        private EndOperationDelegate onEndBuscarCEPDelegate;
        
        private System.Threading.SendOrPostCallback onBuscarCEPCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PesquisaCEPSoapClient() {
        }
        
        public PesquisaCEPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PesquisaCEPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesquisaCEPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesquisaCEPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<BuscarCEPCompletedEventArgs> BuscarCEPCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCEP.PesquisaCEPSoap.BeginBuscarCEP(string pNumCEP, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBuscarCEP(pNumCEP, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ClinVitta.ServiceCEP.PesquisaCEPSoap.EndBuscarCEP(System.IAsyncResult result) {
            return base.Channel.EndBuscarCEP(result);
        }
        
        private System.IAsyncResult OnBeginBuscarCEP(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pNumCEP = ((string)(inValues[0]));
            return ((ClinVitta.ServiceCEP.PesquisaCEPSoap)(this)).BeginBuscarCEP(pNumCEP, callback, asyncState);
        }
        
        private object[] OnEndBuscarCEP(System.IAsyncResult result) {
            string retVal = ((ClinVitta.ServiceCEP.PesquisaCEPSoap)(this)).EndBuscarCEP(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBuscarCEPCompleted(object state) {
            if ((this.BuscarCEPCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BuscarCEPCompleted(this, new BuscarCEPCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BuscarCEPAsync(string pNumCEP) {
            this.BuscarCEPAsync(pNumCEP, null);
        }
        
        public void BuscarCEPAsync(string pNumCEP, object userState) {
            if ((this.onBeginBuscarCEPDelegate == null)) {
                this.onBeginBuscarCEPDelegate = new BeginOperationDelegate(this.OnBeginBuscarCEP);
            }
            if ((this.onEndBuscarCEPDelegate == null)) {
                this.onEndBuscarCEPDelegate = new EndOperationDelegate(this.OnEndBuscarCEP);
            }
            if ((this.onBuscarCEPCompletedDelegate == null)) {
                this.onBuscarCEPCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBuscarCEPCompleted);
            }
            base.InvokeAsync(this.onBeginBuscarCEPDelegate, new object[] {
                        pNumCEP}, this.onEndBuscarCEPDelegate, this.onBuscarCEPCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ClinVitta.ServiceCEP.PesquisaCEPSoap CreateChannel() {
            return new PesquisaCEPSoapClientChannel(this);
        }
        
        private class PesquisaCEPSoapClientChannel : ChannelBase<ClinVitta.ServiceCEP.PesquisaCEPSoap>, ClinVitta.ServiceCEP.PesquisaCEPSoap {
            
            public PesquisaCEPSoapClientChannel(System.ServiceModel.ClientBase<ClinVitta.ServiceCEP.PesquisaCEPSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginBuscarCEP(string pNumCEP, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pNumCEP;
                System.IAsyncResult _result = base.BeginInvoke("BuscarCEP", _args, callback, asyncState);
                return _result;
            }
            
            public string EndBuscarCEP(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("BuscarCEP", _args, result)));
                return _result;
            }
        }
    }
}
