//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ClinVitta.ServiceControledeLogErro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceControledeLogErro.ControledeLogExceptionSoap")]
    public interface ControledeLogExceptionSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PARAMETRO_xxx_WEBSERV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GravaLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGravaLog(string pMensagem, string pDetalhe, string CodUsuario, string COD_PROJETO, string DATAHORA, string ENDERECO_REMOTO, string VERSAO, System.AsyncCallback callback, object asyncState);
        
        void EndGravaLog(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ListaLogsAplicacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginListaLogsAplicacoes(string pCodAplicacao, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceControledeLogErro.CamposLogs[] EndListaLogsAplicacoes(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
                this.RaisePropertyChanged("Any1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CamposLogs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODIGOField;
        
        private string dATA_HORAField;
        
        private string mENSAGEMField;
        
        private string vERSAOField;
        
        private string uSUARIOField;
        
        private string iP_REMOTOField;
        
        private string dETALHE_ERROField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DATA_HORA {
            get {
                return this.dATA_HORAField;
            }
            set {
                this.dATA_HORAField = value;
                this.RaisePropertyChanged("DATA_HORA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MENSAGEM {
            get {
                return this.mENSAGEMField;
            }
            set {
                this.mENSAGEMField = value;
                this.RaisePropertyChanged("MENSAGEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VERSAO {
            get {
                return this.vERSAOField;
            }
            set {
                this.vERSAOField = value;
                this.RaisePropertyChanged("VERSAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string USUARIO {
            get {
                return this.uSUARIOField;
            }
            set {
                this.uSUARIOField = value;
                this.RaisePropertyChanged("USUARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IP_REMOTO {
            get {
                return this.iP_REMOTOField;
            }
            set {
                this.iP_REMOTOField = value;
                this.RaisePropertyChanged("IP_REMOTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DETALHE_ERRO {
            get {
                return this.dETALHE_ERROField;
            }
            set {
                this.dETALHE_ERROField = value;
                this.RaisePropertyChanged("DETALHE_ERRO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControledeLogExceptionSoapChannel : ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PARAMETRO_xxx_WEBSERVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PARAMETRO_xxx_WEBSERVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaLogsAplicacoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaLogsAplicacoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceControledeLogErro.CamposLogs[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceControledeLogErro.CamposLogs[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControledeLogExceptionSoapClient : System.ServiceModel.ClientBase<ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap>, ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap {
        
        private BeginOperationDelegate onBeginPARAMETRO_xxx_WEBSERVDelegate;
        
        private EndOperationDelegate onEndPARAMETRO_xxx_WEBSERVDelegate;
        
        private System.Threading.SendOrPostCallback onPARAMETRO_xxx_WEBSERVCompletedDelegate;
        
        private BeginOperationDelegate onBeginGravaLogDelegate;
        
        private EndOperationDelegate onEndGravaLogDelegate;
        
        private System.Threading.SendOrPostCallback onGravaLogCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaLogsAplicacoesDelegate;
        
        private EndOperationDelegate onEndListaLogsAplicacoesDelegate;
        
        private System.Threading.SendOrPostCallback onListaLogsAplicacoesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ControledeLogExceptionSoapClient() {
        }
        
        public ControledeLogExceptionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControledeLogExceptionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControledeLogExceptionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControledeLogExceptionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<PARAMETRO_xxx_WEBSERVCompletedEventArgs> PARAMETRO_xxx_WEBSERVCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> GravaLogCompleted;
        
        public event System.EventHandler<ListaLogsAplicacoesCompletedEventArgs> ListaLogsAplicacoesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPARAMETRO_xxx_WEBSERV(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
            return base.Channel.EndPARAMETRO_xxx_WEBSERV(result);
        }
        
        private System.IAsyncResult OnBeginPARAMETRO_xxx_WEBSERV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).BeginPARAMETRO_xxx_WEBSERV(callback, asyncState);
        }
        
        private object[] OnEndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
            ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult retVal = ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).EndPARAMETRO_xxx_WEBSERV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPARAMETRO_xxx_WEBSERVCompleted(object state) {
            if ((this.PARAMETRO_xxx_WEBSERVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PARAMETRO_xxx_WEBSERVCompleted(this, new PARAMETRO_xxx_WEBSERVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PARAMETRO_xxx_WEBSERVAsync() {
            this.PARAMETRO_xxx_WEBSERVAsync(null);
        }
        
        public void PARAMETRO_xxx_WEBSERVAsync(object userState) {
            if ((this.onBeginPARAMETRO_xxx_WEBSERVDelegate == null)) {
                this.onBeginPARAMETRO_xxx_WEBSERVDelegate = new BeginOperationDelegate(this.OnBeginPARAMETRO_xxx_WEBSERV);
            }
            if ((this.onEndPARAMETRO_xxx_WEBSERVDelegate == null)) {
                this.onEndPARAMETRO_xxx_WEBSERVDelegate = new EndOperationDelegate(this.OnEndPARAMETRO_xxx_WEBSERV);
            }
            if ((this.onPARAMETRO_xxx_WEBSERVCompletedDelegate == null)) {
                this.onPARAMETRO_xxx_WEBSERVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPARAMETRO_xxx_WEBSERVCompleted);
            }
            base.InvokeAsync(this.onBeginPARAMETRO_xxx_WEBSERVDelegate, null, this.onEndPARAMETRO_xxx_WEBSERVDelegate, this.onPARAMETRO_xxx_WEBSERVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.BeginGravaLog(string pMensagem, string pDetalhe, string CodUsuario, string COD_PROJETO, string DATAHORA, string ENDERECO_REMOTO, string VERSAO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGravaLog(pMensagem, pDetalhe, CodUsuario, COD_PROJETO, DATAHORA, ENDERECO_REMOTO, VERSAO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.EndGravaLog(System.IAsyncResult result) {
            base.Channel.EndGravaLog(result);
        }
        
        private System.IAsyncResult OnBeginGravaLog(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pMensagem = ((string)(inValues[0]));
            string pDetalhe = ((string)(inValues[1]));
            string CodUsuario = ((string)(inValues[2]));
            string COD_PROJETO = ((string)(inValues[3]));
            string DATAHORA = ((string)(inValues[4]));
            string ENDERECO_REMOTO = ((string)(inValues[5]));
            string VERSAO = ((string)(inValues[6]));
            return ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).BeginGravaLog(pMensagem, pDetalhe, CodUsuario, COD_PROJETO, DATAHORA, ENDERECO_REMOTO, VERSAO, callback, asyncState);
        }
        
        private object[] OnEndGravaLog(System.IAsyncResult result) {
            ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).EndGravaLog(result);
            return null;
        }
        
        private void OnGravaLogCompleted(object state) {
            if ((this.GravaLogCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GravaLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GravaLogAsync(string pMensagem, string pDetalhe, string CodUsuario, string COD_PROJETO, string DATAHORA, string ENDERECO_REMOTO, string VERSAO) {
            this.GravaLogAsync(pMensagem, pDetalhe, CodUsuario, COD_PROJETO, DATAHORA, ENDERECO_REMOTO, VERSAO, null);
        }
        
        public void GravaLogAsync(string pMensagem, string pDetalhe, string CodUsuario, string COD_PROJETO, string DATAHORA, string ENDERECO_REMOTO, string VERSAO, object userState) {
            if ((this.onBeginGravaLogDelegate == null)) {
                this.onBeginGravaLogDelegate = new BeginOperationDelegate(this.OnBeginGravaLog);
            }
            if ((this.onEndGravaLogDelegate == null)) {
                this.onEndGravaLogDelegate = new EndOperationDelegate(this.OnEndGravaLog);
            }
            if ((this.onGravaLogCompletedDelegate == null)) {
                this.onGravaLogCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGravaLogCompleted);
            }
            base.InvokeAsync(this.onBeginGravaLogDelegate, new object[] {
                        pMensagem,
                        pDetalhe,
                        CodUsuario,
                        COD_PROJETO,
                        DATAHORA,
                        ENDERECO_REMOTO,
                        VERSAO}, this.onEndGravaLogDelegate, this.onGravaLogCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.BeginListaLogsAplicacoes(string pCodAplicacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaLogsAplicacoes(pCodAplicacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceControledeLogErro.CamposLogs[] ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap.EndListaLogsAplicacoes(System.IAsyncResult result) {
            return base.Channel.EndListaLogsAplicacoes(result);
        }
        
        private System.IAsyncResult OnBeginListaLogsAplicacoes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pCodAplicacao = ((string)(inValues[0]));
            return ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).BeginListaLogsAplicacoes(pCodAplicacao, callback, asyncState);
        }
        
        private object[] OnEndListaLogsAplicacoes(System.IAsyncResult result) {
            ClinVitta.ServiceControledeLogErro.CamposLogs[] retVal = ((ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap)(this)).EndListaLogsAplicacoes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaLogsAplicacoesCompleted(object state) {
            if ((this.ListaLogsAplicacoesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaLogsAplicacoesCompleted(this, new ListaLogsAplicacoesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaLogsAplicacoesAsync(string pCodAplicacao) {
            this.ListaLogsAplicacoesAsync(pCodAplicacao, null);
        }
        
        public void ListaLogsAplicacoesAsync(string pCodAplicacao, object userState) {
            if ((this.onBeginListaLogsAplicacoesDelegate == null)) {
                this.onBeginListaLogsAplicacoesDelegate = new BeginOperationDelegate(this.OnBeginListaLogsAplicacoes);
            }
            if ((this.onEndListaLogsAplicacoesDelegate == null)) {
                this.onEndListaLogsAplicacoesDelegate = new EndOperationDelegate(this.OnEndListaLogsAplicacoes);
            }
            if ((this.onListaLogsAplicacoesCompletedDelegate == null)) {
                this.onListaLogsAplicacoesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaLogsAplicacoesCompleted);
            }
            base.InvokeAsync(this.onBeginListaLogsAplicacoesDelegate, new object[] {
                        pCodAplicacao}, this.onEndListaLogsAplicacoesDelegate, this.onListaLogsAplicacoesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap CreateChannel() {
            return new ControledeLogExceptionSoapClientChannel(this);
        }
        
        private class ControledeLogExceptionSoapClientChannel : ChannelBase<ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap>, ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap {
            
            public ControledeLogExceptionSoapClientChannel(System.ServiceModel.ClientBase<ClinVitta.ServiceControledeLogErro.ControledeLogExceptionSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginPARAMETRO_xxx_WEBSERV(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("PARAMETRO_xxx_WEBSERV", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult EndPARAMETRO_xxx_WEBSERV(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult _result = ((ClinVitta.ServiceControledeLogErro.PARAMETRO_xxx_WEBSERVResponsePARAMETRO_xxx_WEBSERVResult)(base.EndInvoke("PARAMETRO_xxx_WEBSERV", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGravaLog(string pMensagem, string pDetalhe, string CodUsuario, string COD_PROJETO, string DATAHORA, string ENDERECO_REMOTO, string VERSAO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = pMensagem;
                _args[1] = pDetalhe;
                _args[2] = CodUsuario;
                _args[3] = COD_PROJETO;
                _args[4] = DATAHORA;
                _args[5] = ENDERECO_REMOTO;
                _args[6] = VERSAO;
                System.IAsyncResult _result = base.BeginInvoke("GravaLog", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGravaLog(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("GravaLog", _args, result);
            }
            
            public System.IAsyncResult BeginListaLogsAplicacoes(string pCodAplicacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pCodAplicacao;
                System.IAsyncResult _result = base.BeginInvoke("ListaLogsAplicacoes", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceControledeLogErro.CamposLogs[] EndListaLogsAplicacoes(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceControledeLogErro.CamposLogs[] _result = ((ClinVitta.ServiceControledeLogErro.CamposLogs[])(base.EndInvoke("ListaLogsAplicacoes", _args, result)));
                return _result;
            }
        }
    }
}
