//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ClinVitta.ServiceCadastroCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap")]
    public interface Busca_Dados_Cadastro_ClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TipoDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTipoDocumento(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TpDocEmitido[] EndTipoDocumento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TipoOrgaoEmissor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTipoOrgaoEmissor(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] EndTipoOrgaoEmissor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/TipoTelefone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginTipoTelefone(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TpTELEFONE[] EndTipoTelefone(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/BuscaListaUF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginBuscaListaUF(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.ListaUF[] EndBuscaListaUF(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PARAMETROS_CADASTRO_CLIENTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPARAMETROS_CADASTRO_CLIENTE(System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult EndPARAMETROS_CADASTRO_CLIENTE(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GerarCodCli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGerarCodCli(System.AsyncCallback callback, object asyncState);
        
        string EndGerarCodCli(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PesquisaCadastroCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPesquisaCadastroCliente(string pFiltro, string pDADOS, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] EndPesquisaCadastroCliente(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PesquisaCadastroClienteCompleto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPesquisaCadastroClienteCompleto(string pCODCLI, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente EndPesquisaCadastroClienteCompleto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PesquisaTelefoneCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginPesquisaTelefoneCliente(string pCODCLI, System.AsyncCallback callback, object asyncState);
        
        ClinVitta.ServiceCadastroCliente.TpTELEFONE[] EndPesquisaTelefoneCliente(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TpDocEmitido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCTIPODOCField;
        
        private int iDDESCTIPODOCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DESCTIPODOC {
            get {
                return this.dESCTIPODOCField;
            }
            set {
                this.dESCTIPODOCField = value;
                this.RaisePropertyChanged("DESCTIPODOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IDDESCTIPODOC {
            get {
                return this.iDDESCTIPODOCField;
            }
            set {
                this.iDDESCTIPODOCField = value;
                this.RaisePropertyChanged("IDDESCTIPODOC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoCamposCadPaciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nOME_pacienteField;
        
        private string cPF_CNPJField;
        
        private string rG_IEField;
        
        private string emissorField;
        
        private string uf_EmissaoField;
        
        private string sexoField;
        
        private string estado_CivilField;
        
        private string data_NascimentoField;
        
        private string nome_MaeField;
        
        private string nome_PaiField;
        
        private string celularField;
        
        private string fone_FixoField;
        
        private string cepField;
        
        private string ufField;
        
        private string cidadeField;
        
        private string dt_EmissaoField;
        
        private string bairroField;
        
        private string ponto_ReferenciaField;
        
        private string tipo_LogradouroField;
        
        private string desc_LogradouroField;
        
        private string end_NumField;
        
        private string desc_ComplementoField;
        
        private string desc_ObsField;
        
        private string user_CadastroField;
        
        private string data_CadastroField;
        
        private string emailField;
        
        private string tipo_DocField;
        
        private string qt_DependentesField;
        
        private string num_SegField;
        
        private string pessoaField;
        
        private string nome_FantasiaField;
        
        private string tipo_IncricaoField;
        
        private string atividadeField;
        
        private string dt_Inicio_AtividadeField;
        
        private string dt_JuntaField;
        
        private string dt_Ult_Alt_ContratualField;
        
        private string capital_SocialField;
        
        private string faturamento_MensalField;
        
        private string resp_ComercialField;
        
        private string resp_Comercial_Tel_FixoField;
        
        private string resp_Comercial_CelularField;
        
        private string dtVenceDocField;
        
        private string fILIAL_CADField;
        
        private string nOSSOCLIENTEField;
        
        private string pRIMERAHABILITACAOField;
        
        private string cATEGORIAHABILITACAOField;
        
        private string dATAVENCHABILITACAOField;
        
        private string rENACHEField;
        
        private string oBS_HABILITACAOField;
        
        private string nUMEROREGISTROField;
        
        private string profissaoField;
        
        private string cODCLIField;
        
        private string oBSGERALCADASTROField;
        
        private string nOMEField;
        
        private string rgField;
        
        private string cPFField;
        
        private string nome_pacienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NOME_paciente {
            get {
                return this.nOME_pacienteField;
            }
            set {
                this.nOME_pacienteField = value;
                this.RaisePropertyChanged("NOME_paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CPF_CNPJ {
            get {
                return this.cPF_CNPJField;
            }
            set {
                this.cPF_CNPJField = value;
                this.RaisePropertyChanged("CPF_CNPJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RG_IE {
            get {
                return this.rG_IEField;
            }
            set {
                this.rG_IEField = value;
                this.RaisePropertyChanged("RG_IE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Emissor {
            get {
                return this.emissorField;
            }
            set {
                this.emissorField = value;
                this.RaisePropertyChanged("Emissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Uf_Emissao {
            get {
                return this.uf_EmissaoField;
            }
            set {
                this.uf_EmissaoField = value;
                this.RaisePropertyChanged("Uf_Emissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estado_Civil {
            get {
                return this.estado_CivilField;
            }
            set {
                this.estado_CivilField = value;
                this.RaisePropertyChanged("Estado_Civil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Data_Nascimento {
            get {
                return this.data_NascimentoField;
            }
            set {
                this.data_NascimentoField = value;
                this.RaisePropertyChanged("Data_Nascimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Nome_Mae {
            get {
                return this.nome_MaeField;
            }
            set {
                this.nome_MaeField = value;
                this.RaisePropertyChanged("Nome_Mae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Nome_Pai {
            get {
                return this.nome_PaiField;
            }
            set {
                this.nome_PaiField = value;
                this.RaisePropertyChanged("Nome_Pai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Fone_Fixo {
            get {
                return this.fone_FixoField;
            }
            set {
                this.fone_FixoField = value;
                this.RaisePropertyChanged("Fone_Fixo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("Cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("Uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Dt_Emissao {
            get {
                return this.dt_EmissaoField;
            }
            set {
                this.dt_EmissaoField = value;
                this.RaisePropertyChanged("Dt_Emissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Ponto_Referencia {
            get {
                return this.ponto_ReferenciaField;
            }
            set {
                this.ponto_ReferenciaField = value;
                this.RaisePropertyChanged("Ponto_Referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Tipo_Logradouro {
            get {
                return this.tipo_LogradouroField;
            }
            set {
                this.tipo_LogradouroField = value;
                this.RaisePropertyChanged("Tipo_Logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Desc_Logradouro {
            get {
                return this.desc_LogradouroField;
            }
            set {
                this.desc_LogradouroField = value;
                this.RaisePropertyChanged("Desc_Logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string End_Num {
            get {
                return this.end_NumField;
            }
            set {
                this.end_NumField = value;
                this.RaisePropertyChanged("End_Num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Desc_Complemento {
            get {
                return this.desc_ComplementoField;
            }
            set {
                this.desc_ComplementoField = value;
                this.RaisePropertyChanged("Desc_Complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Desc_Obs {
            get {
                return this.desc_ObsField;
            }
            set {
                this.desc_ObsField = value;
                this.RaisePropertyChanged("Desc_Obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string User_Cadastro {
            get {
                return this.user_CadastroField;
            }
            set {
                this.user_CadastroField = value;
                this.RaisePropertyChanged("User_Cadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Data_Cadastro {
            get {
                return this.data_CadastroField;
            }
            set {
                this.data_CadastroField = value;
                this.RaisePropertyChanged("Data_Cadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Tipo_Doc {
            get {
                return this.tipo_DocField;
            }
            set {
                this.tipo_DocField = value;
                this.RaisePropertyChanged("Tipo_Doc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Qt_Dependentes {
            get {
                return this.qt_DependentesField;
            }
            set {
                this.qt_DependentesField = value;
                this.RaisePropertyChanged("Qt_Dependentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Num_Seg {
            get {
                return this.num_SegField;
            }
            set {
                this.num_SegField = value;
                this.RaisePropertyChanged("Num_Seg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Pessoa {
            get {
                return this.pessoaField;
            }
            set {
                this.pessoaField = value;
                this.RaisePropertyChanged("Pessoa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Nome_Fantasia {
            get {
                return this.nome_FantasiaField;
            }
            set {
                this.nome_FantasiaField = value;
                this.RaisePropertyChanged("Nome_Fantasia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Tipo_Incricao {
            get {
                return this.tipo_IncricaoField;
            }
            set {
                this.tipo_IncricaoField = value;
                this.RaisePropertyChanged("Tipo_Incricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Atividade {
            get {
                return this.atividadeField;
            }
            set {
                this.atividadeField = value;
                this.RaisePropertyChanged("Atividade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Dt_Inicio_Atividade {
            get {
                return this.dt_Inicio_AtividadeField;
            }
            set {
                this.dt_Inicio_AtividadeField = value;
                this.RaisePropertyChanged("Dt_Inicio_Atividade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Dt_Junta {
            get {
                return this.dt_JuntaField;
            }
            set {
                this.dt_JuntaField = value;
                this.RaisePropertyChanged("Dt_Junta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Dt_Ult_Alt_Contratual {
            get {
                return this.dt_Ult_Alt_ContratualField;
            }
            set {
                this.dt_Ult_Alt_ContratualField = value;
                this.RaisePropertyChanged("Dt_Ult_Alt_Contratual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Capital_Social {
            get {
                return this.capital_SocialField;
            }
            set {
                this.capital_SocialField = value;
                this.RaisePropertyChanged("Capital_Social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Faturamento_Mensal {
            get {
                return this.faturamento_MensalField;
            }
            set {
                this.faturamento_MensalField = value;
                this.RaisePropertyChanged("Faturamento_Mensal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Resp_Comercial {
            get {
                return this.resp_ComercialField;
            }
            set {
                this.resp_ComercialField = value;
                this.RaisePropertyChanged("Resp_Comercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Resp_Comercial_Tel_Fixo {
            get {
                return this.resp_Comercial_Tel_FixoField;
            }
            set {
                this.resp_Comercial_Tel_FixoField = value;
                this.RaisePropertyChanged("Resp_Comercial_Tel_Fixo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Resp_Comercial_Celular {
            get {
                return this.resp_Comercial_CelularField;
            }
            set {
                this.resp_Comercial_CelularField = value;
                this.RaisePropertyChanged("Resp_Comercial_Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string dtVenceDoc {
            get {
                return this.dtVenceDocField;
            }
            set {
                this.dtVenceDocField = value;
                this.RaisePropertyChanged("dtVenceDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string FILIAL_CAD {
            get {
                return this.fILIAL_CADField;
            }
            set {
                this.fILIAL_CADField = value;
                this.RaisePropertyChanged("FILIAL_CAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string NOSSOCLIENTE {
            get {
                return this.nOSSOCLIENTEField;
            }
            set {
                this.nOSSOCLIENTEField = value;
                this.RaisePropertyChanged("NOSSOCLIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string PRIMERAHABILITACAO {
            get {
                return this.pRIMERAHABILITACAOField;
            }
            set {
                this.pRIMERAHABILITACAOField = value;
                this.RaisePropertyChanged("PRIMERAHABILITACAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string CATEGORIAHABILITACAO {
            get {
                return this.cATEGORIAHABILITACAOField;
            }
            set {
                this.cATEGORIAHABILITACAOField = value;
                this.RaisePropertyChanged("CATEGORIAHABILITACAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string DATAVENCHABILITACAO {
            get {
                return this.dATAVENCHABILITACAOField;
            }
            set {
                this.dATAVENCHABILITACAOField = value;
                this.RaisePropertyChanged("DATAVENCHABILITACAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string RENACHE {
            get {
                return this.rENACHEField;
            }
            set {
                this.rENACHEField = value;
                this.RaisePropertyChanged("RENACHE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string OBS_HABILITACAO {
            get {
                return this.oBS_HABILITACAOField;
            }
            set {
                this.oBS_HABILITACAOField = value;
                this.RaisePropertyChanged("OBS_HABILITACAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string NUMEROREGISTRO {
            get {
                return this.nUMEROREGISTROField;
            }
            set {
                this.nUMEROREGISTROField = value;
                this.RaisePropertyChanged("NUMEROREGISTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Profissao {
            get {
                return this.profissaoField;
            }
            set {
                this.profissaoField = value;
                this.RaisePropertyChanged("Profissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string CODCLI {
            get {
                return this.cODCLIField;
            }
            set {
                this.cODCLIField = value;
                this.RaisePropertyChanged("CODCLI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string OBSGERALCADASTRO {
            get {
                return this.oBSGERALCADASTROField;
            }
            set {
                this.oBSGERALCADASTROField = value;
                this.RaisePropertyChanged("OBSGERALCADASTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string NOME {
            get {
                return this.nOMEField;
            }
            set {
                this.nOMEField = value;
                this.RaisePropertyChanged("NOME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
                this.RaisePropertyChanged("RG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
                this.RaisePropertyChanged("CPF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string Nome_paciente {
            get {
                return this.nome_pacienteField;
            }
            set {
                this.nome_pacienteField = value;
                this.RaisePropertyChanged("Nome_paciente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ufField;
        
        private int iDUFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IDUF {
            get {
                return this.iDUFField;
            }
            set {
                this.iDUFField = value;
                this.RaisePropertyChanged("IDUF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TpTELEFONE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private int cODTPTELField;
        
        private string tipoField;
        
        private string foneField;
        
        private string dddField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CODTPTEL {
            get {
                return this.cODTPTELField;
            }
            set {
                this.cODTPTELField = value;
                this.RaisePropertyChanged("CODTPTEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Fone {
            get {
                return this.foneField;
            }
            set {
                this.foneField = value;
                this.RaisePropertyChanged("Fone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ddd {
            get {
                return this.dddField;
            }
            set {
                this.dddField = value;
                this.RaisePropertyChanged("Ddd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TipoOrgaoEmissorDoc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeOrgaoField;
        
        private int codNomeOrgaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NomeOrgao {
            get {
                return this.nomeOrgaoField;
            }
            set {
                this.nomeOrgaoField = value;
                this.RaisePropertyChanged("NomeOrgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CodNomeOrgao {
            get {
                return this.codNomeOrgaoField;
            }
            set {
                this.codNomeOrgaoField = value;
                this.RaisePropertyChanged("CodNomeOrgao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1 {
            get {
                return this.any1Field;
            }
            set {
                this.any1Field = value;
                this.RaisePropertyChanged("Any1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Busca_Dados_Cadastro_ClienteSoapChannel : ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TipoDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TpDocEmitido[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TpDocEmitido[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoOrgaoEmissorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TipoOrgaoEmissorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoTelefoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TipoTelefoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TpTELEFONE[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TpTELEFONE[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuscaListaUFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BuscaListaUFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.ListaUF[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.ListaUF[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PARAMETROS_CADASTRO_CLIENTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PARAMETROS_CADASTRO_CLIENTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GerarCodCliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GerarCodCliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesquisaCadastroClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PesquisaCadastroClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesquisaCadastroClienteCompletoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PesquisaCadastroClienteCompletoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesquisaTelefoneClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PesquisaTelefoneClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClinVitta.ServiceCadastroCliente.TpTELEFONE[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClinVitta.ServiceCadastroCliente.TpTELEFONE[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Busca_Dados_Cadastro_ClienteSoapClient : System.ServiceModel.ClientBase<ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap>, ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap {
        
        private BeginOperationDelegate onBeginTipoDocumentoDelegate;
        
        private EndOperationDelegate onEndTipoDocumentoDelegate;
        
        private System.Threading.SendOrPostCallback onTipoDocumentoCompletedDelegate;
        
        private BeginOperationDelegate onBeginTipoOrgaoEmissorDelegate;
        
        private EndOperationDelegate onEndTipoOrgaoEmissorDelegate;
        
        private System.Threading.SendOrPostCallback onTipoOrgaoEmissorCompletedDelegate;
        
        private BeginOperationDelegate onBeginTipoTelefoneDelegate;
        
        private EndOperationDelegate onEndTipoTelefoneDelegate;
        
        private System.Threading.SendOrPostCallback onTipoTelefoneCompletedDelegate;
        
        private BeginOperationDelegate onBeginBuscaListaUFDelegate;
        
        private EndOperationDelegate onEndBuscaListaUFDelegate;
        
        private System.Threading.SendOrPostCallback onBuscaListaUFCompletedDelegate;
        
        private BeginOperationDelegate onBeginPARAMETROS_CADASTRO_CLIENTEDelegate;
        
        private EndOperationDelegate onEndPARAMETROS_CADASTRO_CLIENTEDelegate;
        
        private System.Threading.SendOrPostCallback onPARAMETROS_CADASTRO_CLIENTECompletedDelegate;
        
        private BeginOperationDelegate onBeginGerarCodCliDelegate;
        
        private EndOperationDelegate onEndGerarCodCliDelegate;
        
        private System.Threading.SendOrPostCallback onGerarCodCliCompletedDelegate;
        
        private BeginOperationDelegate onBeginPesquisaCadastroClienteDelegate;
        
        private EndOperationDelegate onEndPesquisaCadastroClienteDelegate;
        
        private System.Threading.SendOrPostCallback onPesquisaCadastroClienteCompletedDelegate;
        
        private BeginOperationDelegate onBeginPesquisaCadastroClienteCompletoDelegate;
        
        private EndOperationDelegate onEndPesquisaCadastroClienteCompletoDelegate;
        
        private System.Threading.SendOrPostCallback onPesquisaCadastroClienteCompletoCompletedDelegate;
        
        private BeginOperationDelegate onBeginPesquisaTelefoneClienteDelegate;
        
        private EndOperationDelegate onEndPesquisaTelefoneClienteDelegate;
        
        private System.Threading.SendOrPostCallback onPesquisaTelefoneClienteCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Busca_Dados_Cadastro_ClienteSoapClient() {
        }
        
        public Busca_Dados_Cadastro_ClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Busca_Dados_Cadastro_ClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Busca_Dados_Cadastro_ClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Busca_Dados_Cadastro_ClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<TipoDocumentoCompletedEventArgs> TipoDocumentoCompleted;
        
        public event System.EventHandler<TipoOrgaoEmissorCompletedEventArgs> TipoOrgaoEmissorCompleted;
        
        public event System.EventHandler<TipoTelefoneCompletedEventArgs> TipoTelefoneCompleted;
        
        public event System.EventHandler<BuscaListaUFCompletedEventArgs> BuscaListaUFCompleted;
        
        public event System.EventHandler<PARAMETROS_CADASTRO_CLIENTECompletedEventArgs> PARAMETROS_CADASTRO_CLIENTECompleted;
        
        public event System.EventHandler<GerarCodCliCompletedEventArgs> GerarCodCliCompleted;
        
        public event System.EventHandler<PesquisaCadastroClienteCompletedEventArgs> PesquisaCadastroClienteCompleted;
        
        public event System.EventHandler<PesquisaCadastroClienteCompletoCompletedEventArgs> PesquisaCadastroClienteCompletoCompleted;
        
        public event System.EventHandler<PesquisaTelefoneClienteCompletedEventArgs> PesquisaTelefoneClienteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginTipoDocumento(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTipoDocumento(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TpDocEmitido[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndTipoDocumento(System.IAsyncResult result) {
            return base.Channel.EndTipoDocumento(result);
        }
        
        private System.IAsyncResult OnBeginTipoDocumento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginTipoDocumento(callback, asyncState);
        }
        
        private object[] OnEndTipoDocumento(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TpDocEmitido[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndTipoDocumento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTipoDocumentoCompleted(object state) {
            if ((this.TipoDocumentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TipoDocumentoCompleted(this, new TipoDocumentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TipoDocumentoAsync() {
            this.TipoDocumentoAsync(null);
        }
        
        public void TipoDocumentoAsync(object userState) {
            if ((this.onBeginTipoDocumentoDelegate == null)) {
                this.onBeginTipoDocumentoDelegate = new BeginOperationDelegate(this.OnBeginTipoDocumento);
            }
            if ((this.onEndTipoDocumentoDelegate == null)) {
                this.onEndTipoDocumentoDelegate = new EndOperationDelegate(this.OnEndTipoDocumento);
            }
            if ((this.onTipoDocumentoCompletedDelegate == null)) {
                this.onTipoDocumentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTipoDocumentoCompleted);
            }
            base.InvokeAsync(this.onBeginTipoDocumentoDelegate, null, this.onEndTipoDocumentoDelegate, this.onTipoDocumentoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginTipoOrgaoEmissor(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTipoOrgaoEmissor(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndTipoOrgaoEmissor(System.IAsyncResult result) {
            return base.Channel.EndTipoOrgaoEmissor(result);
        }
        
        private System.IAsyncResult OnBeginTipoOrgaoEmissor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginTipoOrgaoEmissor(callback, asyncState);
        }
        
        private object[] OnEndTipoOrgaoEmissor(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndTipoOrgaoEmissor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTipoOrgaoEmissorCompleted(object state) {
            if ((this.TipoOrgaoEmissorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TipoOrgaoEmissorCompleted(this, new TipoOrgaoEmissorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TipoOrgaoEmissorAsync() {
            this.TipoOrgaoEmissorAsync(null);
        }
        
        public void TipoOrgaoEmissorAsync(object userState) {
            if ((this.onBeginTipoOrgaoEmissorDelegate == null)) {
                this.onBeginTipoOrgaoEmissorDelegate = new BeginOperationDelegate(this.OnBeginTipoOrgaoEmissor);
            }
            if ((this.onEndTipoOrgaoEmissorDelegate == null)) {
                this.onEndTipoOrgaoEmissorDelegate = new EndOperationDelegate(this.OnEndTipoOrgaoEmissor);
            }
            if ((this.onTipoOrgaoEmissorCompletedDelegate == null)) {
                this.onTipoOrgaoEmissorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTipoOrgaoEmissorCompleted);
            }
            base.InvokeAsync(this.onBeginTipoOrgaoEmissorDelegate, null, this.onEndTipoOrgaoEmissorDelegate, this.onTipoOrgaoEmissorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginTipoTelefone(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTipoTelefone(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TpTELEFONE[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndTipoTelefone(System.IAsyncResult result) {
            return base.Channel.EndTipoTelefone(result);
        }
        
        private System.IAsyncResult OnBeginTipoTelefone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginTipoTelefone(callback, asyncState);
        }
        
        private object[] OnEndTipoTelefone(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TpTELEFONE[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndTipoTelefone(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTipoTelefoneCompleted(object state) {
            if ((this.TipoTelefoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TipoTelefoneCompleted(this, new TipoTelefoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TipoTelefoneAsync() {
            this.TipoTelefoneAsync(null);
        }
        
        public void TipoTelefoneAsync(object userState) {
            if ((this.onBeginTipoTelefoneDelegate == null)) {
                this.onBeginTipoTelefoneDelegate = new BeginOperationDelegate(this.OnBeginTipoTelefone);
            }
            if ((this.onEndTipoTelefoneDelegate == null)) {
                this.onEndTipoTelefoneDelegate = new EndOperationDelegate(this.OnEndTipoTelefone);
            }
            if ((this.onTipoTelefoneCompletedDelegate == null)) {
                this.onTipoTelefoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTipoTelefoneCompleted);
            }
            base.InvokeAsync(this.onBeginTipoTelefoneDelegate, null, this.onEndTipoTelefoneDelegate, this.onTipoTelefoneCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginBuscaListaUF(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBuscaListaUF(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.ListaUF[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndBuscaListaUF(System.IAsyncResult result) {
            return base.Channel.EndBuscaListaUF(result);
        }
        
        private System.IAsyncResult OnBeginBuscaListaUF(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginBuscaListaUF(callback, asyncState);
        }
        
        private object[] OnEndBuscaListaUF(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.ListaUF[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndBuscaListaUF(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBuscaListaUFCompleted(object state) {
            if ((this.BuscaListaUFCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BuscaListaUFCompleted(this, new BuscaListaUFCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BuscaListaUFAsync() {
            this.BuscaListaUFAsync(null);
        }
        
        public void BuscaListaUFAsync(object userState) {
            if ((this.onBeginBuscaListaUFDelegate == null)) {
                this.onBeginBuscaListaUFDelegate = new BeginOperationDelegate(this.OnBeginBuscaListaUF);
            }
            if ((this.onEndBuscaListaUFDelegate == null)) {
                this.onEndBuscaListaUFDelegate = new EndOperationDelegate(this.OnEndBuscaListaUF);
            }
            if ((this.onBuscaListaUFCompletedDelegate == null)) {
                this.onBuscaListaUFCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBuscaListaUFCompleted);
            }
            base.InvokeAsync(this.onBeginBuscaListaUFDelegate, null, this.onEndBuscaListaUFDelegate, this.onBuscaListaUFCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginPARAMETROS_CADASTRO_CLIENTE(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPARAMETROS_CADASTRO_CLIENTE(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndPARAMETROS_CADASTRO_CLIENTE(System.IAsyncResult result) {
            return base.Channel.EndPARAMETROS_CADASTRO_CLIENTE(result);
        }
        
        private System.IAsyncResult OnBeginPARAMETROS_CADASTRO_CLIENTE(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginPARAMETROS_CADASTRO_CLIENTE(callback, asyncState);
        }
        
        private object[] OnEndPARAMETROS_CADASTRO_CLIENTE(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndPARAMETROS_CADASTRO_CLIENTE(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPARAMETROS_CADASTRO_CLIENTECompleted(object state) {
            if ((this.PARAMETROS_CADASTRO_CLIENTECompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PARAMETROS_CADASTRO_CLIENTECompleted(this, new PARAMETROS_CADASTRO_CLIENTECompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PARAMETROS_CADASTRO_CLIENTEAsync() {
            this.PARAMETROS_CADASTRO_CLIENTEAsync(null);
        }
        
        public void PARAMETROS_CADASTRO_CLIENTEAsync(object userState) {
            if ((this.onBeginPARAMETROS_CADASTRO_CLIENTEDelegate == null)) {
                this.onBeginPARAMETROS_CADASTRO_CLIENTEDelegate = new BeginOperationDelegate(this.OnBeginPARAMETROS_CADASTRO_CLIENTE);
            }
            if ((this.onEndPARAMETROS_CADASTRO_CLIENTEDelegate == null)) {
                this.onEndPARAMETROS_CADASTRO_CLIENTEDelegate = new EndOperationDelegate(this.OnEndPARAMETROS_CADASTRO_CLIENTE);
            }
            if ((this.onPARAMETROS_CADASTRO_CLIENTECompletedDelegate == null)) {
                this.onPARAMETROS_CADASTRO_CLIENTECompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPARAMETROS_CADASTRO_CLIENTECompleted);
            }
            base.InvokeAsync(this.onBeginPARAMETROS_CADASTRO_CLIENTEDelegate, null, this.onEndPARAMETROS_CADASTRO_CLIENTEDelegate, this.onPARAMETROS_CADASTRO_CLIENTECompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginGerarCodCli(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGerarCodCli(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndGerarCodCli(System.IAsyncResult result) {
            return base.Channel.EndGerarCodCli(result);
        }
        
        private System.IAsyncResult OnBeginGerarCodCli(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginGerarCodCli(callback, asyncState);
        }
        
        private object[] OnEndGerarCodCli(System.IAsyncResult result) {
            string retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndGerarCodCli(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGerarCodCliCompleted(object state) {
            if ((this.GerarCodCliCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GerarCodCliCompleted(this, new GerarCodCliCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GerarCodCliAsync() {
            this.GerarCodCliAsync(null);
        }
        
        public void GerarCodCliAsync(object userState) {
            if ((this.onBeginGerarCodCliDelegate == null)) {
                this.onBeginGerarCodCliDelegate = new BeginOperationDelegate(this.OnBeginGerarCodCli);
            }
            if ((this.onEndGerarCodCliDelegate == null)) {
                this.onEndGerarCodCliDelegate = new EndOperationDelegate(this.OnEndGerarCodCli);
            }
            if ((this.onGerarCodCliCompletedDelegate == null)) {
                this.onGerarCodCliCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGerarCodCliCompleted);
            }
            base.InvokeAsync(this.onBeginGerarCodCliDelegate, null, this.onEndGerarCodCliDelegate, this.onGerarCodCliCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginPesquisaCadastroCliente(string pFiltro, string pDADOS, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPesquisaCadastroCliente(pFiltro, pDADOS, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndPesquisaCadastroCliente(System.IAsyncResult result) {
            return base.Channel.EndPesquisaCadastroCliente(result);
        }
        
        private System.IAsyncResult OnBeginPesquisaCadastroCliente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pFiltro = ((string)(inValues[0]));
            string pDADOS = ((string)(inValues[1]));
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginPesquisaCadastroCliente(pFiltro, pDADOS, callback, asyncState);
        }
        
        private object[] OnEndPesquisaCadastroCliente(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndPesquisaCadastroCliente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPesquisaCadastroClienteCompleted(object state) {
            if ((this.PesquisaCadastroClienteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PesquisaCadastroClienteCompleted(this, new PesquisaCadastroClienteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PesquisaCadastroClienteAsync(string pFiltro, string pDADOS) {
            this.PesquisaCadastroClienteAsync(pFiltro, pDADOS, null);
        }
        
        public void PesquisaCadastroClienteAsync(string pFiltro, string pDADOS, object userState) {
            if ((this.onBeginPesquisaCadastroClienteDelegate == null)) {
                this.onBeginPesquisaCadastroClienteDelegate = new BeginOperationDelegate(this.OnBeginPesquisaCadastroCliente);
            }
            if ((this.onEndPesquisaCadastroClienteDelegate == null)) {
                this.onEndPesquisaCadastroClienteDelegate = new EndOperationDelegate(this.OnEndPesquisaCadastroCliente);
            }
            if ((this.onPesquisaCadastroClienteCompletedDelegate == null)) {
                this.onPesquisaCadastroClienteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPesquisaCadastroClienteCompleted);
            }
            base.InvokeAsync(this.onBeginPesquisaCadastroClienteDelegate, new object[] {
                        pFiltro,
                        pDADOS}, this.onEndPesquisaCadastroClienteDelegate, this.onPesquisaCadastroClienteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginPesquisaCadastroClienteCompleto(string pCODCLI, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPesquisaCadastroClienteCompleto(pCODCLI, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndPesquisaCadastroClienteCompleto(System.IAsyncResult result) {
            return base.Channel.EndPesquisaCadastroClienteCompleto(result);
        }
        
        private System.IAsyncResult OnBeginPesquisaCadastroClienteCompleto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pCODCLI = ((string)(inValues[0]));
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginPesquisaCadastroClienteCompleto(pCODCLI, callback, asyncState);
        }
        
        private object[] OnEndPesquisaCadastroClienteCompleto(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndPesquisaCadastroClienteCompleto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPesquisaCadastroClienteCompletoCompleted(object state) {
            if ((this.PesquisaCadastroClienteCompletoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PesquisaCadastroClienteCompletoCompleted(this, new PesquisaCadastroClienteCompletoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PesquisaCadastroClienteCompletoAsync(string pCODCLI) {
            this.PesquisaCadastroClienteCompletoAsync(pCODCLI, null);
        }
        
        public void PesquisaCadastroClienteCompletoAsync(string pCODCLI, object userState) {
            if ((this.onBeginPesquisaCadastroClienteCompletoDelegate == null)) {
                this.onBeginPesquisaCadastroClienteCompletoDelegate = new BeginOperationDelegate(this.OnBeginPesquisaCadastroClienteCompleto);
            }
            if ((this.onEndPesquisaCadastroClienteCompletoDelegate == null)) {
                this.onEndPesquisaCadastroClienteCompletoDelegate = new EndOperationDelegate(this.OnEndPesquisaCadastroClienteCompleto);
            }
            if ((this.onPesquisaCadastroClienteCompletoCompletedDelegate == null)) {
                this.onPesquisaCadastroClienteCompletoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPesquisaCadastroClienteCompletoCompleted);
            }
            base.InvokeAsync(this.onBeginPesquisaCadastroClienteCompletoDelegate, new object[] {
                        pCODCLI}, this.onEndPesquisaCadastroClienteCompletoDelegate, this.onPesquisaCadastroClienteCompletoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.BeginPesquisaTelefoneCliente(string pCODCLI, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPesquisaTelefoneCliente(pCODCLI, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinVitta.ServiceCadastroCliente.TpTELEFONE[] ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap.EndPesquisaTelefoneCliente(System.IAsyncResult result) {
            return base.Channel.EndPesquisaTelefoneCliente(result);
        }
        
        private System.IAsyncResult OnBeginPesquisaTelefoneCliente(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pCODCLI = ((string)(inValues[0]));
            return ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).BeginPesquisaTelefoneCliente(pCODCLI, callback, asyncState);
        }
        
        private object[] OnEndPesquisaTelefoneCliente(System.IAsyncResult result) {
            ClinVitta.ServiceCadastroCliente.TpTELEFONE[] retVal = ((ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap)(this)).EndPesquisaTelefoneCliente(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPesquisaTelefoneClienteCompleted(object state) {
            if ((this.PesquisaTelefoneClienteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PesquisaTelefoneClienteCompleted(this, new PesquisaTelefoneClienteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PesquisaTelefoneClienteAsync(string pCODCLI) {
            this.PesquisaTelefoneClienteAsync(pCODCLI, null);
        }
        
        public void PesquisaTelefoneClienteAsync(string pCODCLI, object userState) {
            if ((this.onBeginPesquisaTelefoneClienteDelegate == null)) {
                this.onBeginPesquisaTelefoneClienteDelegate = new BeginOperationDelegate(this.OnBeginPesquisaTelefoneCliente);
            }
            if ((this.onEndPesquisaTelefoneClienteDelegate == null)) {
                this.onEndPesquisaTelefoneClienteDelegate = new EndOperationDelegate(this.OnEndPesquisaTelefoneCliente);
            }
            if ((this.onPesquisaTelefoneClienteCompletedDelegate == null)) {
                this.onPesquisaTelefoneClienteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPesquisaTelefoneClienteCompleted);
            }
            base.InvokeAsync(this.onBeginPesquisaTelefoneClienteDelegate, new object[] {
                        pCODCLI}, this.onEndPesquisaTelefoneClienteDelegate, this.onPesquisaTelefoneClienteCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap CreateChannel() {
            return new Busca_Dados_Cadastro_ClienteSoapClientChannel(this);
        }
        
        private class Busca_Dados_Cadastro_ClienteSoapClientChannel : ChannelBase<ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap>, ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap {
            
            public Busca_Dados_Cadastro_ClienteSoapClientChannel(System.ServiceModel.ClientBase<ClinVitta.ServiceCadastroCliente.Busca_Dados_Cadastro_ClienteSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginTipoDocumento(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TipoDocumento", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TpDocEmitido[] EndTipoDocumento(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TpDocEmitido[] _result = ((ClinVitta.ServiceCadastroCliente.TpDocEmitido[])(base.EndInvoke("TipoDocumento", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTipoOrgaoEmissor(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TipoOrgaoEmissor", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] EndTipoOrgaoEmissor(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[] _result = ((ClinVitta.ServiceCadastroCliente.TipoOrgaoEmissorDoc[])(base.EndInvoke("TipoOrgaoEmissor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTipoTelefone(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TipoTelefone", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TpTELEFONE[] EndTipoTelefone(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TpTELEFONE[] _result = ((ClinVitta.ServiceCadastroCliente.TpTELEFONE[])(base.EndInvoke("TipoTelefone", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBuscaListaUF(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("BuscaListaUF", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.ListaUF[] EndBuscaListaUF(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.ListaUF[] _result = ((ClinVitta.ServiceCadastroCliente.ListaUF[])(base.EndInvoke("BuscaListaUF", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPARAMETROS_CADASTRO_CLIENTE(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("PARAMETROS_CADASTRO_CLIENTE", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult EndPARAMETROS_CADASTRO_CLIENTE(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult _result = ((ClinVitta.ServiceCadastroCliente.PARAMETROS_CADASTRO_CLIENTEResponsePARAMETROS_CADASTRO_CLIENTEResult)(base.EndInvoke("PARAMETROS_CADASTRO_CLIENTE", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGerarCodCli(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GerarCodCli", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGerarCodCli(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GerarCodCli", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPesquisaCadastroCliente(string pFiltro, string pDADOS, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = pFiltro;
                _args[1] = pDADOS;
                System.IAsyncResult _result = base.BeginInvoke("PesquisaCadastroCliente", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] EndPesquisaCadastroCliente(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[] _result = ((ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente[])(base.EndInvoke("PesquisaCadastroCliente", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPesquisaCadastroClienteCompleto(string pCODCLI, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pCODCLI;
                System.IAsyncResult _result = base.BeginInvoke("PesquisaCadastroClienteCompleto", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente EndPesquisaCadastroClienteCompleto(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente _result = ((ClinVitta.ServiceCadastroCliente.TipoCamposCadPaciente)(base.EndInvoke("PesquisaCadastroClienteCompleto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPesquisaTelefoneCliente(string pCODCLI, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pCODCLI;
                System.IAsyncResult _result = base.BeginInvoke("PesquisaTelefoneCliente", _args, callback, asyncState);
                return _result;
            }
            
            public ClinVitta.ServiceCadastroCliente.TpTELEFONE[] EndPesquisaTelefoneCliente(System.IAsyncResult result) {
                object[] _args = new object[0];
                ClinVitta.ServiceCadastroCliente.TpTELEFONE[] _result = ((ClinVitta.ServiceCadastroCliente.TpTELEFONE[])(base.EndInvoke("PesquisaTelefoneCliente", _args, result)));
                return _result;
            }
        }
    }
}
