//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ClinVitta.ServiceDataHora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDataHora.Retorna_Data_HoraSoap")]
    public interface Retorna_Data_HoraSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RetornaDataHoraServidor_MySql", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRetornaDataHoraServidor_MySql(int Tipo, System.AsyncCallback callback, object asyncState);
        
        string EndRetornaDataHoraServidor_MySql(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Retorna_Data_HoraSoapChannel : ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetornaDataHoraServidor_MySqlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetornaDataHoraServidor_MySqlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Retorna_Data_HoraSoapClient : System.ServiceModel.ClientBase<ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap>, ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap {
        
        private BeginOperationDelegate onBeginRetornaDataHoraServidor_MySqlDelegate;
        
        private EndOperationDelegate onEndRetornaDataHoraServidor_MySqlDelegate;
        
        private System.Threading.SendOrPostCallback onRetornaDataHoraServidor_MySqlCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Retorna_Data_HoraSoapClient() {
        }
        
        public Retorna_Data_HoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Retorna_Data_HoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Retorna_Data_HoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Retorna_Data_HoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetornaDataHoraServidor_MySqlCompletedEventArgs> RetornaDataHoraServidor_MySqlCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap.BeginRetornaDataHoraServidor_MySql(int Tipo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetornaDataHoraServidor_MySql(Tipo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap.EndRetornaDataHoraServidor_MySql(System.IAsyncResult result) {
            return base.Channel.EndRetornaDataHoraServidor_MySql(result);
        }
        
        private System.IAsyncResult OnBeginRetornaDataHoraServidor_MySql(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Tipo = ((int)(inValues[0]));
            return ((ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap)(this)).BeginRetornaDataHoraServidor_MySql(Tipo, callback, asyncState);
        }
        
        private object[] OnEndRetornaDataHoraServidor_MySql(System.IAsyncResult result) {
            string retVal = ((ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap)(this)).EndRetornaDataHoraServidor_MySql(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetornaDataHoraServidor_MySqlCompleted(object state) {
            if ((this.RetornaDataHoraServidor_MySqlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetornaDataHoraServidor_MySqlCompleted(this, new RetornaDataHoraServidor_MySqlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetornaDataHoraServidor_MySqlAsync(int Tipo) {
            this.RetornaDataHoraServidor_MySqlAsync(Tipo, null);
        }
        
        public void RetornaDataHoraServidor_MySqlAsync(int Tipo, object userState) {
            if ((this.onBeginRetornaDataHoraServidor_MySqlDelegate == null)) {
                this.onBeginRetornaDataHoraServidor_MySqlDelegate = new BeginOperationDelegate(this.OnBeginRetornaDataHoraServidor_MySql);
            }
            if ((this.onEndRetornaDataHoraServidor_MySqlDelegate == null)) {
                this.onEndRetornaDataHoraServidor_MySqlDelegate = new EndOperationDelegate(this.OnEndRetornaDataHoraServidor_MySql);
            }
            if ((this.onRetornaDataHoraServidor_MySqlCompletedDelegate == null)) {
                this.onRetornaDataHoraServidor_MySqlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetornaDataHoraServidor_MySqlCompleted);
            }
            base.InvokeAsync(this.onBeginRetornaDataHoraServidor_MySqlDelegate, new object[] {
                        Tipo}, this.onEndRetornaDataHoraServidor_MySqlDelegate, this.onRetornaDataHoraServidor_MySqlCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap CreateChannel() {
            return new Retorna_Data_HoraSoapClientChannel(this);
        }
        
        private class Retorna_Data_HoraSoapClientChannel : ChannelBase<ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap>, ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap {
            
            public Retorna_Data_HoraSoapClientChannel(System.ServiceModel.ClientBase<ClinVitta.ServiceDataHora.Retorna_Data_HoraSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetornaDataHoraServidor_MySql(int Tipo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Tipo;
                System.IAsyncResult _result = base.BeginInvoke("RetornaDataHoraServidor_MySql", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRetornaDataHoraServidor_MySql(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RetornaDataHoraServidor_MySql", _args, result)));
                return _result;
            }
        }
    }
}
